name: l3build
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  l3build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: teatimeguest/setup-texlive-action@v2
        with:
          packages: ffcode libertine minted fvextra catchfile xstring framed tcolorbox environ pgf l3build
      - run: l3build ctan -q --show-log-on-error
