name: l3build
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  l3build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get -y install ghostscript
      - uses: teatimeguest/setup-texlive-action@v2.5.0
        with:
          update-all-packages: true
          package-file: DEPENDS.txt
          packages: scheme-basic xetex ffcode libertine minted fvextra catchfile xstring framed tcolorbox environ pgf l3build docshots
      - run: l3build check -q --show-log-on-error
